//
// Created by mcleans on 9/30/23.
//

#ifndef ROBOT_CONTROLLER_PINOUT_CONFIG_H
#define ROBOT_CONTROLLER_PINOUT_CONFIG_H

#define ROBOT_CONTROLLER_PINOUT_GATEWAY_UART_RX 3
#define ROBOT_CONTROLLER_PINOUT_GATEWAY_UART_TX 2
#define ROBOT_CONTROLLER_PINOUT_GATEWAY_UART USART2
#define ROBOT_CONTROLLER_PINOUT_GATEWAY_UART_BAUD 9600
#define ROBOT_CONTROLLER_PINOUT_GATEWAY_UART_PORT GPIOA

#endif //ROBOT_CONTROLLER_PINOUT_CONFIG_H
