name: robot-ci

on:
  push:
    branches: [ "main", "develop", "f/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: sudo apt install gcc-arm-none-eabi cmake
      
    - name: Create Build Directory
      run: mkdir cmake_build && mkdir cmake_build/release

    - name: Configure CMake
      run: cmake cmake_build/release

    - name: Build
      run: cmake --build cmake_build/release

    - name: Save Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release_binary
        path: cmake_build/release/6dofRobotController.bin
        
