name: robot-ci

on:
  push:
    branches: [ "main", "develop", "f/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: sudo apt install gcc-arm-none-eabi make
      
    - name: Compile Code
      run: make
      
    - name: Save Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release_binary
        path: build/main.bin
        
